language: c
sudo: required
os: linux
dist: trusty

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y make unrar-free autoconf automake libtool gcc g++ gperf flex \
                            bison texinfo gawk ncurses-dev libexpat-dev python-dev python \
                            python-serial sed git unzip bash help2man wget bzip2 libtool-bin

install:
  - git clone --recursive https://github.com/pfalcon/esp-open-sdk.git ~/esp-open-sdk
  - cd ~/esp-open-sdk && make STANDALONE=y
